### PR TITLE
Updated ReadMe with spelling tweak

### PR DESCRIPTION
**Pull request by acorncom**
Nice work on all of this!

### CODE REVIEW

**Comment by samdark** [comment]
Thanks!

**Comment by acorncom** [comment]
@samdark I was reading over things and have seen various places I could make small improvements (sometimes with spelling and other small wording changes).  If I find the time, would you mind if I send over a number of tweaks / changes to text? I wouldn't change the meaning of things, just would clean the English up a bit ...

**Comment by ddinchev** [comment]
I'd vote for that! Just maybe do it in single PR, or at least single per article - not to pollute the repository history and not to create too much noise for the people watching ;)

**Comment by samdark** [comment]
@acorncom sure, you're very welcome to do that. If you'll find wrong things, send pull requests as well. Same if you have additional recipes.

**Comment by acorncom** [comment]
Sounds good guys.  Life's been a bit hectic recently, but will add to my todo and revisit in a bit ;-)

**Pull request merged**
