### PR TITLE
fix the assignment of where to CarQuery

### PR DESCRIPTION
**Pull request by langshuang**

### CODE REVIEW

**Comment by githubjeka** [comment]
https://github.com/samdark/yii2-cookbook/pull/52

**Comment by samdark** [comment]
Have you checked that it works?

**Comment by langshuang** [comment]
Yes, I have already been verified. My version is 2.0.4. If you use where to pass parameters, CarQuery.php file $this->type is NULL. You must use $this->where to receive.

**Comment by samdark** [comment]
Thanks!

**Pull request merged**
