### PR TITLE
fixed RbacController::actionAssign

### PR DESCRIPTION
**Pull request by damasco**

### CODE REVIEW

**Comment by samdark** [comment]
I think just `role` is a better name.

**Comment by damasco** [comment]
@samdark 

```php
if (!$role) {
    throw new InvalidParamException("There is no role \"$role\".");
}
```

**Comment by samdark** [comment]
Ah. Got the idea. Still, I think the argument should be `$role`. Let's rename role object instead.

**Comment by samdark** [comment]
Fixed. Thank you!

**Pull request closed without merging**
