### PR TITLE
New recipe

### PR DESCRIPTION
**Pull request by summerknight**
About pretty URL and pagination

### CODE REVIEW

**Comment by samdark** [comment]
:+1:

**Comment by summerknight** [comment]
Samdark, what is this? Preliminary estimation? :)

**Comment by samdark** [comment]
Yes. I like the idea.

**Comment by summerknight** [comment]
Is it possible to use such rule:
```php
'search-vuz/<page:\d+>/<per-page>' => 'site/search-vuz',
```
Problem is with dash symbol in parameter `per-page`
This is a default URL parameter name for `yii\data\Pagination` object to set `pageSize` property

**Comment by samdark** [comment]
Try escaping dash with `-`.

**Comment by summerknight** [comment]
like this? 
```php
'search-vuz/<page:\d+>/<per\-page>' => 'site/search-vuz',
```
It doesn't work also

**Comment by samdark** [comment]
Then I have no idea. Need to dig into it.

**Comment by summerknight** [comment]
What do you think? Is it ok to write a recipe about pagination + pretty url with instruction to change pageSize URL param name?

**Comment by samdark** [comment]
Yep.

**Comment by summerknight** [comment]
Another question :) Why pull request is still open? Because you have to check code before merging?

**Comment by samdark** [comment]
Yes. Code, wording etc.

**Comment by samdark** [comment]
Merged. Will adjust later.

**Comment by samdark** [comment]
Thank you!

**Pull request merged**
