### PR TITLE
Create Auditing fields Created By,Modified By,Created At,Modified At

### PR DESCRIPTION
**Pull request by vishwasrao**
This will help users to create & use auditing fields in web applications easily.

### CODE REVIEW

**Comment by summerknight** [comment]
It is essential recipe but not formatted yet

**Comment by padlyuck** [comment]
@summerknight Created By,Modified By see https://github.com/yiisoft/yii2/blob/master/framework/behaviors/BlameableBehavior.php

**Comment by samdark** [comment]
@summerknight do you have time to expand it?

**Comment by samdark** [comment]
Closing since can't use it in the form it is.

**Pull request closed without merging**
